ifndef top_dir
problem:
	@echo "your Makefile must define top_dir before including Makefile.config"
	exit 1
endif

bin_dir=$(shell readlink -f $(top_dir)/bin)
include_dir=$(shell readlink -f $(top_dir)/include)
obj_dir=$(shell readlink -f $(cur_dir)/obj)

CXX = g++
CXXFLAGS = -I$(include_dir) -Wall -g -std=c++11 -Wextra -pedantic `pkg-config --cflags libpmemobj++`
LDFLAGS = -I$(include_dir) -lpthread `pkg-config --libs libpmemobj++`

RM=$(shell which rm) -rf
CP=$(shell which cp) -f
MV=$(shell which mv) -f
MKDIR=$(shell which mkdir) -p
PROG=PLsmStore_Debug

dirs:
	@$(MKDIR) $(bin_dir)
	@$(MKDIR) $(obj_dir)

.DEFAULT_GOAL := all

